In [1]:
import numpy as np
import math

## 1

Найти ближайшую ортогональную матрицу (в смысле нормы Фробениуса) к матрице. Вывести результат в консоль и, посмотрев на него, найти соответствующие этому преобразованию угол и направление поворота.

In [2]:
a = np.array([
    [0.5, 2.16506351, 0.4330127],
    [-0.8660254, 1.25, 0.25],
    [0.0, 0.5, 2.5]
])
u, d, vt = np.linalg.svd(a)
result = np.matmul(u, vt)
print('A:', a, '\n','Nearest orthogonal:', result, sep='\n')

A:
[[ 0.5         2.16506351  0.4330127 ]
 [-0.8660254   1.25        0.25      ]
 [ 0.          0.5         2.5       ]]


Nearest orthogonal:
[[ 5.00000000e-01  8.66025404e-01 -3.87999547e-10]
 [-8.66025404e-01  5.00000000e-01  1.65510349e-11]
 [ 2.08333332e-10  3.27741999e-10  1.00000000e+00]]


In [3]:
def find_angle_and_rotation_axis(rotation):
    if np.allclose(rotation[0][0], [1.0]):
        axis = 'x'
        cos_a = rotation[1][1]
    elif np.allclose(rotation[1][1], [1.0]):
        axis = 'y'
        cos_a = rotation[0][0]
    elif np.allclose(rotation[2][2], [1.0]):
        axis = 'z'
        cos_a = rotation[0][0]
    else:
        raise ValueError('not a rotation matrix')
    
    alpha = np.arccos(cos_a) * 180 / math.pi
    print(f'{alpha} degrees rotation around `{axis}` axis')
    

find_angle_and_rotation_axis(result)

59.99999997514016 degrees rotation around `z` axis


## 2

При помощи SVD найти обратную матрицу к квадратной матрице nxn, состоящей из элементов Aij = 1/(i +j - 1) для размеров матрицы n=3 и n=10

In [4]:
def generate_and_invert(n):
    a = np.array([[1 / (i + j - 1) if i + j - 1 != 0 else 0 for j in range(n)] for i in range(n)], dtype=np.float64)
    u, d, vt = np.linalg.svd(a)
    d_inv = np.diag(d ** -1)
    a_inv = np.matmul(np.matmul(vt.T, d_inv), u.T)
    if not np.allclose(a_inv, np.linalg.inv(a)):
        raise ValueError('Inverse matrix is not close to default implementation (np.linalg.inv)')
    print('A:', a, '', 'A -1:', a_inv, '\n', sep='\n')

generate_and_invert(n=3)
generate_and_invert(n=10)

A:
[[-1.          0.          1.        ]
 [ 0.          1.          0.5       ]
 [ 1.          0.5         0.33333333]]

A -1:
[[-0.07692308 -0.46153846  0.92307692]
 [-0.46153846  1.23076923 -0.46153846]
 [ 0.92307692 -0.46153846  0.92307692]]


A:
[[-1.          0.          1.          0.5         0.33333333  0.25
   0.2         0.16666667  0.14285714  0.125     ]
 [ 0.          1.          0.5         0.33333333  0.25        0.2
   0.16666667  0.14285714  0.125       0.11111111]
 [ 1.          0.5         0.33333333  0.25        0.2         0.16666667
   0.14285714  0.125       0.11111111  0.1       ]
 [ 0.5         0.33333333  0.25        0.2         0.16666667  0.14285714
   0.125       0.11111111  0.1         0.09090909]
 [ 0.33333333  0.25        0.2         0.16666667  0.14285714  0.125
   0.11111111  0.1         0.09090909  0.08333333]
 [ 0.25        0.2         0.16666667  0.14285714  0.125       0.11111111
   0.1         0.09090909  0.08333333  0.07692308]
 [ 0.2         0.

## 3

Для квадратной матрицы nxn, состоящей из элементов Aij = i + j - 1, найти с использованием SVD все решения уравнений AX=0 для n=4

In [5]:
def generate_and_solve(n):
    a = np.array([[i + j - 1 for j in range(n)] for i in range(n)], dtype=np.float64)
    print('A:', a, '', sep='\n')

    u, d, vt = np.linalg.svd(a)

    threshold = 1e-15
    for eigenvalue, right_vector in zip(d, vt.T):
        if eigenvalue > -threshold and eigenvalue < threshold:
            print('Solution:', right_vector)

generate_and_solve(4)

A:
[[-1.  0.  1.  2.]
 [ 0.  1.  2.  3.]
 [ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]]

Solution: [ 5.47722558e-01 -1.52655666e-16 -7.47481003e-01 -3.75861876e-01]
Solution: [ 0.73029674 -0.40824829  0.54719667 -0.02399583]
